DROP TABLE EMBROIDERY CASCADE;
-- DROP TABLE CATALOG CASCADE;
DROP TABLE COLOR CASCADE;
DROP TABLE THREAD CASCADE;
-- DROP TABLE CATEGORY CASCADE;
-- DROP TABLE PRODUCT CASCADE;
-- DROP TABLE CATEGORY_PRODUCT CASCADE;
-- DROP TABLE BUTTONS CASCADE;



CREATE TABLE EMBROIDERY(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME CHARACTER VARYING(50) UNIQUE NOT NULL,
    HEIGHT REAL NOT NULL,
    WIDTH REAL NOT NULL,
    PHOTO_LINK TEXT,
    REL_PATH TEXT,
    TIME NUMERIC
);

-- CREATE TABLE CATALOG(
--     ID SERIAL PRIMARY KEY NOT NULL, 
--     NAME CHARACTER VARYING(50) NOT NULL
-- );


CREATE TABLE COLOR(
    ID INTEGER NOT NULL, 
    CATALOG_ID INTEGER NOT NULL,
    NAME CHARACTER VARYING(50) NOT NULL, 
    COUNT INTEGER DEFAULT 0 CHECK (COUNT >= 0),
    PRIMARY KEY (ID),
    FOREIGN KEY (CATALOG_ID) REFERENCES CATALOG(ID)
);

CREATE TABLE THREAD (
    COLOR_ID INTEGER NOT NULL,
    EMBROIDERY_ID BIGINT NOT NULL,
    INDEX INTEGER NOT NULL,
    LENGTH REAL NOT NULL,
    PRIMARY KEY (INDEX, EMBROIDERY_ID),
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR (ID),
    FOREIGN KEY (EMBROIDERY_ID) REFERENCES EMBROIDERY (ID)
);

-- CREATE TABLE CATEGORY (
--     ID SERIAL NOT NULL,
--     NAME CHARACTER VARYING(50) NOT NULL,
--     PRIMARY KEY (ID)
-- );


-- CREATE TABLE PRODUCT (
--     ID SERIAL NOT NULL,
--     NAME CHARACTER VARYING(200) NOT NULL,
--     DESCRIPTION CHARACTER VARYING(350),
--     PRIMARY KEY (ID)
-- );

-- CREATE TABLE CATEGORY_PRODUCT(
--     CATEGORY_ID INTEGER NOT NULL,
--     PRODUCT_ID INTEGER NOT NULL,
--     EMBROIDERY_ID BIGINT,
--     PRICE REAL NOT NULL,
--     SIZE CHARACTER VARYING(50)

--     PRIMARY KEY(CATEGORY_ID,PRODUCT_ID),

--     FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY (ID),
--     FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT (ID),
--     FOREIGN KEY(EMBROIDERY_ID) REFERENCES EMBROIDERY(ID) 
-- );


-- CREATE TABLE BUTTONS(
--     ID SERIAL NOT NULL,
--     SUB CHARACTER VARYING(200) NOT NULL,
--     LINK_TO CHARACTER VARYING(200) NOT NULL,
--     F_NAME CHARACTER VARYING(200),
--     ARGS TEXT,
--     SHOW_ON BOOLEAN,
--     PR INTEGER NOT NULL,
--     PRIMARY KEY (ID)
-- );